services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"

  go-backend:
    image: golang:1.23-alpine
    working_dir: /app
    volumes:
      - ./server/go:/app
      - /app/pkg/mod
    command: sh -c "go mod download && go run ./src/main.go"
    ports:
      - "8081:8080"

  java-backend:
    image: maven:4.0.0-rc-5-eclipse-temurin-25-noble
    working_dir: /app
    volumes:
      - ./server/java:/app
      - /app/.m2
    command: sh -c "mvn -f /app/pom.xml spring-boot:run"
    ports:
      - "8082:8080"
