services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./client:/app
      - ./server/java/src/main/resources/certs:/app/certs:ro
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"

  go-backend:
    image: projectea-go-dev
    build:
      context: ./server/go
      target: build
    entrypoint: ""
    working_dir: /app
    volumes:
      - ./server/go:/app
      - /app/pkg/mod
    command: sh -c "go mod download && go run ./src"
    ports:
      - "8081:8081"

  java-backend:
    image: projectea-java-dev
    build:
      context: ./server/java
      target: build
    entrypoint: ""
    working_dir: /app
    volumes:
      - ./server/java:/app
      - maven-cache:/root/.m2
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:adminpassword@mongodb:27017/projectea_nosql?authSource=admin
    command: sh -c "chmod +x mvnw && ./mvnw spring-boot:run"
    ports:
      - "8082:8082"
    depends_on:
      - oracle-db

  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server/java/src/main/resources/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - java-backend

  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=ProjecTeaPPS
      - APP_USER=ProjecTeaDB
      - APP_USER_PASSWORD=ProjecTeaPPS
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
  
  mongodb:
    image: mongo:latest
    container_name: projectea_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=projectea_nosql
    volumes:
      - mongodb_data:/data/db


volumes:
  oracle-data:
  maven-cache:
  mongodb_data:
